# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23bd12bd4fd359c33ac92ba95d17941dd757292853fe295ee2a1a1d32b0c114f8682d537b508f002cc0edfa11a5b6ee06d3d2872466ce316e52eae37b6a5862a

test:
  secret_key_base: 1a0d4284463bf20cbda9faf648104b7789f54f0176b73b5c7a8ae66bfe7f1c284ad313269af4013857bb455ff3bb5c96b7fc1e9c4ba8092281fbfa70770d998b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
